<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UJ1ABA6" failures="2" tests="8" name="Retry Mutiple Failed Test Cases" time="0.27" errors="0" timestamp="2022-04-28T21:53:38 IST">
  <testcase classname="mytests.MyTest" name="Test1" time="0.035">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTest" name="Test1" time="0.007">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTest" name="Test1" time="0.006">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTest" name="Test1" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTest.Test1(MyTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTest" name="Test2" time="0.008">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTest" name="Test2" time="0.012">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTest" name="Test2" time="0.004">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTest" name="Test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTest.Test2(MyTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Retry Mutiple Failed Test Cases -->
